# Trading Pairs to Monitor
trading_pairs:
  - BTC/USDT
  - ETH/USDT
  - SOL/USDT

# Time Interval for Data Fetching
time_interval: "1m"

# Number of Historical Data Points to Fetch
data_points: 100

# Leverage for Trading
leverage: 5

# Trading Frequency in Seconds
trading_frequency: 60